"""initial schema

Revision ID: 25aac297abba
Revises: 
Create Date: 2026-07-26 12:04:26.808664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25aac297abba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('avatar_initials', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('relationship_other', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_remind_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_frequency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('member_invites')
    op.drop_table('family_members')
    # ### end Alembic commands ###
